name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install Dependencies
      run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

    - name: Run Artisan Commands
      run: php artisan storage:link
    - name: Publish Cloudinary Config
      run: php artisan vendor:publish --provider="CloudinaryLabs\CloudinaryLaravel\CloudinaryServiceProvider" --tag="cloudinary-laravel-config"

    - name: Directory Permissions
      run: chmod -R 777 storage public bootstrap/cache
